"""added image attribute to Manufacturer

Revision ID: a35d59a068e7
Revises: abed61b6b249
Create Date: 2023-11-01 13:32:45.857432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35d59a068e7'
down_revision = 'abed61b6b249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
